/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    authors: Author;
    tags: Tag;
    guides: Guide;
    'guide-categories': GuideCategory;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'guide-categories': GuideCategoriesSelect<false> | GuideCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'main-menu': MainMenu;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessible description of the image
   */
  alt?: string | null;
  caption?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The URL slug for the page (e.g. "about", "contact"). Use "home" for the homepage.
   */
  slug: string;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHeader';
          }
        | {
            title: string;
            text?: string | null;
            media: number | Media;
            cta?: {
              primaryLabel?: string | null;
              primaryPage?: (number | null) | Page;
              secondaryLabel?: string | null;
              secondaryPage?: (number | null) | Page;
            };
            benefits?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            subtitle?: string | null;
            features?:
              | {
                  icon: number | Media;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title: string;
            subtitle?: string | null;
            testimonials?:
              | {
                  name: string;
                  title: string;
                  testimonial: string;
                  date: string;
                  photo?: (number | null) | Media;
                  linkedin?: string | null;
                  facebook?: string | null;
                  xTwitter?: string | null;
                  instagram?: string | null;
                  telegram?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            cardLeft: {
              image?: (number | null) | Media;
              title: string;
              items?:
                | {
                    text: string;
                    details?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            cardRight: {
              image?: (number | null) | Media;
              title: string;
              items?:
                | {
                    text: string;
                    details?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardsType1';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            showTableOfContents?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'longText';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * If unchecked, this page will be hidden from public access and menus.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Main article title
   */
  title: string;
  /**
   * Preview text for lists (SEO description by default)
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_html?: string | null;
  seo?: {
    /**
     * Leave empty to use article title
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use short description
     */
    metaDescription?: string | null;
    /**
     * Leave empty to use main image
     */
    metaImage?: (number | null) | Media;
  };
  /**
   * Article URL (automatically generated from title if empty)
   */
  slug?: string | null;
  publishedAt?: string | null;
  author: number | Author;
  category: number | Category;
  tags?: (number | Tag)[] | null;
  relatedPosts?: (number | Post)[] | null;
  /**
   * Calculated automatically on save
   */
  readTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Full author name
   */
  name: string;
  /**
   * URL-friendly identifier (e.g. maria-shevchenko)
   */
  slug: string;
  /**
   * Author photo for blog display
   */
  photo?: (number | null) | Media;
  /**
   * Short biography (2-3 sentences)
   */
  bio?: string | null;
  /**
   * Position or role (e.g. CEO, Immigration Expert)
   */
  role?: string | null;
  /**
   * Links to social media profiles
   */
  socialLinks?: {
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * Facebook profile URL
     */
    facebook?: string | null;
    /**
     * Telegram URL or username
     */
    telegram?: string | null;
  };
  /**
   * Link to CMS user account (optional)
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin: Full access including settings. Manager: Content management only.
   */
  role: 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category name for website display
   */
  name: string;
  /**
   * URL-friendly identifier (e.g. instructions, taxes)
   */
  slug: string;
  /**
   * Category description for SEO and category page
   */
  description?: string | null;
  /**
   * Sorting order (lower number = higher in list)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name for website display
   */
  name: string;
  /**
   * URL-friendly identifier (e.g. digital-nomad)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  /**
   * Guide title
   */
  title: string;
  /**
   * Auto-generated from title if empty
   */
  slug: string;
  /**
   * 150–200 characters for cards and SEO
   */
  excerpt: string;
  category: number | GuideCategory;
  featuredImage?: (number | null) | Media;
  /**
   * Shown at the top of the guide
   */
  summary?: {
    /**
     * e.g. €50–100
     */
    totalCost?: string | null;
    /**
     * e.g. 2–3 months
     */
    estimatedDuration?: string | null;
    /**
     * How the procedure is done
     */
    format?: ('online' | 'hybrid' | 'offline')[] | null;
    /**
     * e.g. Residency, NIE, e-signature
     */
    requirements?:
      | {
          requirement: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Guide accuracy as of this date
     */
    lastUpdated?: string | null;
  };
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  introduction_html?: string | null;
  steps?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        content_html?: string | null;
        /**
         * e.g. 15–30 min
         */
        estimatedTime?: string | null;
        difficulty?: ('easy' | 'medium' | 'hard') | null;
        requiredDocuments?:
          | {
              document: string;
              id?: string | null;
            }[]
          | null;
        callouts?:
          | {
              type: 'info' | 'warning' | 'alert' | 'success';
              title?: string | null;
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'callout';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'guideStep';
      }[]
    | null;
  conclusion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  conclusion_html?: string | null;
  resources?:
    | {
        title: string;
        url: string;
        type?: ('website' | 'pdf' | 'video' | 'form') | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        answer_html?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-categories".
 */
export interface GuideCategory {
  id: number;
  /**
   * Category name (e.g. Visas, Documents, Vehicles)
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name if empty)
   */
  slug: string;
  /**
   * Category description for listing page
   */
  description?: string | null;
  /**
   * Lucide icon name (e.g. FileText, Car, Heart)
   */
  icon?: string | null;
  /**
   * Sorting order (lower number = higher in list)
   */
  order?: number | null;
  /**
   * Hex color for badges (e.g. #3b82f6)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'guide-categories';
        value: number | GuideCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageHeader?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              title?: T;
              text?: T;
              media?: T;
              cta?:
                | T
                | {
                    primaryLabel?: T;
                    primaryPage?: T;
                    secondaryLabel?: T;
                    secondaryPage?: T;
                  };
              benefits?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              subtitle?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    title?: T;
                    testimonial?: T;
                    date?: T;
                    photo?: T;
                    linkedin?: T;
                    facebook?: T;
                    xTwitter?: T;
                    instagram?: T;
                    telegram?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardsType1?:
          | T
          | {
              cardLeft?:
                | T
                | {
                    image?: T;
                    title?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          details?: T;
                          id?: T;
                        };
                  };
              cardRight?:
                | T
                | {
                    image?: T;
                    title?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          details?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        longText?:
          | T
          | {
              content?: T;
              showTableOfContents?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  content_html?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  slug?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  tags?: T;
  relatedPosts?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  role?: T;
  socialLinks?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        facebook?: T;
        telegram?: T;
      };
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  featuredImage?: T;
  summary?:
    | T
    | {
        totalCost?: T;
        estimatedDuration?: T;
        format?: T;
        requirements?:
          | T
          | {
              requirement?: T;
              id?: T;
            };
        lastUpdated?: T;
      };
  introduction?: T;
  introduction_html?: T;
  steps?:
    | T
    | {
        guideStep?:
          | T
          | {
              title?: T;
              content?: T;
              content_html?: T;
              estimatedTime?: T;
              difficulty?: T;
              requiredDocuments?:
                | T
                | {
                    document?: T;
                    id?: T;
                  };
              callouts?:
                | T
                | {
                    callout?:
                      | T
                      | {
                          type?: T;
                          title?: T;
                          content?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  conclusion?: T;
  conclusion_html?: T;
  resources?:
    | T
    | {
        title?: T;
        url?: T;
        type?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        answer_html?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-categories_select".
 */
export interface GuideCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  maintenance?: {
    /**
     * If enabled, only logged-in users will be able to access the site.
     */
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * Displayed at XL and 2XL breakpoints (240×48 px). Use SVG or PNG with a transparent background.
   */
  logoLarge?: (number | null) | Media;
  /**
   * Displayed at SM, MD and LG breakpoints (170×40 px). Use SVG or PNG with a transparent background.
   */
  logoMedium?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        link: number | Page;
        id?: string | null;
      }[]
    | null;
  ctaPrimary?: {
    label?: string | null;
    link?: (number | null) | Page;
  };
  ctaSecondary?: {
    label?: string | null;
    link?: (number | null) | Page;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Displayed at LG, XL and 2XL breakpoints (240×48 px). Use SVG or PNG with a transparent background.
   */
  logoLarge?: (number | null) | Media;
  /**
   * Displayed at SM and MD breakpoints (170×40 px). Use SVG or PNG with a transparent background.
   */
  logoMedium?: (number | null) | Media;
  /**
   * Text displayed below the logo in the footer.
   */
  slogan?: string | null;
  navItems?:
    | {
        label: string;
        link?: (number | null) | Page;
        /**
         * Use this only if not linking to an internal page.
         */
        externalLink?: string | null;
        id?: string | null;
      }[]
    | null;
  resourceItems?:
    | {
        label: string;
        link?: (number | null) | Page;
        /**
         * Use this only if not linking to an internal page.
         */
        externalLink?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'xTwitter' | 'twitter' | 'linkedin' | 'youtube' | 'telegram' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  serviceLinks?:
    | {
        label: string;
        link?: (number | null) | Page;
        /**
         * Use this only if not linking to an internal page.
         */
        externalLink?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  maintenance?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  logoLarge?: T;
  logoMedium?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  ctaPrimary?:
    | T
    | {
        label?: T;
        link?: T;
      };
  ctaSecondary?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoLarge?: T;
  logoMedium?: T;
  slogan?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        externalLink?: T;
        id?: T;
      };
  resourceItems?:
    | T
    | {
        label?: T;
        link?: T;
        externalLink?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  serviceLinks?:
    | T
    | {
        label?: T;
        link?: T;
        externalLink?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}